services:
  python-helium: # NOT WORKING
    image: "python:3.12"
    user: root
    working_dir: /app
    volumes:
      - ${PWD}:/app
      - ${OUTPUT_DIR:-${PWD}/output}:/app/output
    command: sh -c "pip install --quiet selenium-wire && python main.py --url=\"${URL}\" --file-prefix=\"${FILE_PREFIX}\" --ws-browser=\"${WS_BROWSER}\" --proxy-ip=\"${PROXY_IP}\""
    environment:
      - URL
      - OUTPUT_DIR=./output
      - FILE_PREFIX=capture
      - WS_BROWSER
      - PROXY_IP
