services:
  javascript-selenium: #NOT WORKING
    image: "node:22"
    user: root
    working_dir: /app
    volumes:
      - ${PWD}:/app
      - ${OUTPUT_DIR:-${PWD}/output}:/app/output
    command: >
      sh -c "
        apt-get update &&
        apt-get install -y libnss3 libatk-bridge2.0-0 libdrm2 libxkbcommon0 libgbm1 libasound2 &&
        npm install &&
        node main.js --url=\"${URL}\" --file-prefix=\"${FILE_PREFIX}\" --ws-browser=\"${WS_BROWSER}\" --proxy-ip=\"${PROXY_IP}\"
      "
    environment:
      - URL
      - OUTPUT_DIR=./output
      - FILE_PREFIX=capture
      - WS_BROWSER
      - PROXY_IP
