services:
  python-playwright:
    image: "mcr.microsoft.com/playwright/python:v1.55.0-noble"
    user: root
    working_dir: /app
    network_mode: ${NETWORK_NAME:-default}
    volumes:
      - ${PWD}:/app
      - ${OUTPUT_DIR:-${PWD}/output}:/app/output
    command: sh -c "pip install --quiet playwright && python main.py --url=\"${URL}\" --file-prefix=\"${FILE_PREFIX}\" --ws-browser=\"${WS_BROWSER}\" --proxy-ip=\"${PROXY_IP}\""
    environment:
      - URL
      - OUTPUT_DIR=./output
      - FILE_PREFIX=capture
      - WS_BROWSER
      - PROXY_IP
